### PR TITLE
New: tmpfiles and variale file names

### PR DESCRIPTION
**Pull request by libcrack**
- Implemented mktemp for creating temporary files to avoid symlinks attacks
- Several lines wrapper to fit the standard 80 cols
- Implemented variable file names

### CODE REVIEW

**Comment by libcrack** [comment]
hey mate,

would it be possible to review & (hopefully) merge the changes? :-)

**Comment by graysky2** [comment]
Forgot about this... will review shortly.

**Comment by libcrack** [comment]
cheers :-)

**Comment by graysky2** [comment]
Looks solid. Thanks for the contribution.

**Pull request merged**
